# Generated by Django 5.1.2 on 2024-12-03 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventario', '0001_initial'),
        ('Trazabilidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='fk_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignacion_actividad',
            name='fk_actividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trazabilidad.actividad'),
        ),
        migrations.AddField(
            model_name='asignacion_actividad',
            name='fk_inventario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventario.inventario'),
        ),
        migrations.AddField(
            model_name='asignacion_actividad',
            name='fk_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='afeccion',
            name='fk_bancal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trazabilidad.bancal'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='fk_bancal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trazabilidad.bancal'),
        ),
        migrations.AddField(
            model_name='control',
            name='fk_afeccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trazabilidad.afeccion'),
        ),
        migrations.AddField(
            model_name='control',
            name='fk_cultivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trazabilidad.cultivo'),
        ),
        migrations.AddField(
            model_name='bancal',
            name='fk_cultivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trazabilidad.cultivo'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='fk_especie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trazabilidad.especie'),
        ),
        migrations.AddField(
            model_name='bancal',
            name='fk_lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trazabilidad.lote'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fk_actividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trazabilidad.actividad'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fk_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='afeccion',
            name='fk_plaga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trazabilidad.plaga'),
        ),
        migrations.AddField(
            model_name='semillero',
            name='fk_especie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trazabilidad.especie'),
        ),
        migrations.AddField(
            model_name='semillero',
            name='fk_lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trazabilidad.lote'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='fk_semillero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trazabilidad.semillero'),
        ),
        migrations.AddField(
            model_name='especie',
            name='fk_tipo_especie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trazabilidad.tipo_especie'),
        ),
        migrations.AddField(
            model_name='plaga',
            name='fk_tipo_plaga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trazabilidad.tipo_plaga'),
        ),
    ]
