# Generated by Django 5.1.2 on 2024-12-03 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Finanzas', '0001_initial'),
        ('Trazabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='fk_asignacion_actividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trazabilidad.asignacion_actividad'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='fk_cultivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trazabilidad.cultivo'),
        ),
    ]
