# Generated by Django 5.1.2 on 2024-12-03 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Finanzas', '0002_initial'),
        ('Trazabilidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='fk_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='residuo',
            name='fk_cultivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trazabilidad.cultivo'),
        ),
        migrations.AddField(
            model_name='venta',
            name='fk_produccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finanzas.produccion'),
        ),
    ]
