# Generated by Django 5.1.3 on 2025-02-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='fk_bancal',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='fk_configuracion',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='fk_tipo_sensor',
        ),
        migrations.AddField(
            model_name='sensor',
            name='nombre_sensor',
            field=models.CharField(default='Default Nombre Sensor', max_length=50),
        ),
        migrations.AddField(
            model_name='sensor',
            name='tipo_sensor',
            field=models.CharField(default='Default Tipo Sensor', max_length=50),
        ),
        migrations.AddField(
            model_name='sensor',
            name='ubicacion',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='unidad_medida',
            field=models.CharField(default='Default unidad_medida', max_length=50),
        ),
        migrations.AddField(
            model_name='sensor',
            name='valor_max',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='valor_min',
            field=models.FloatField(default=0.0),
        ),
    ]
