# Generated by Django 5.1.3 on 2025-03-01 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT', '0004_sensor_cultivo'),
        ('Trazabilidad', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='cultivo',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='nombre_sensor',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='tipo_sensor',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='unidad_medida',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='valor_max',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='valor_min',
        ),
        migrations.AddField(
            model_name='sensor',
            name='fk_bancal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trazabilidad.bancal'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='fk_configuracion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IoT.configuracion'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='fk_tipo_sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IoT.tipo_sensor'),
        ),
    ]
