# Generated by Django 5.1.3 on 2025-03-02 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT', '0005_remove_sensor_cultivo_remove_sensor_nombre_sensor_and_more'),
        ('Trazabilidad', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='fk_cultivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trazabilidad.cultivo'),
        ),
    ]
