# Generated by Django 5.1.3 on 2025-03-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT', '0006_sensor_fk_cultivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='medicion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='valor_max',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='valor_min',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
