# Generated by Django 5.1.2 on 2024-12-03 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('unidades', models.IntegerField()),
                ('precioCU', models.FloatField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('tipo_empacado', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('unidadMedida', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_herramienta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventario.herramienta')),
                ('fk_insumo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventario.insumo')),
            ],
        ),
        migrations.AddField(
            model_name='herramienta',
            name='fk_tipo_herramienta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventario.tipo_herramienta'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='fk_tipo_insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventario.tipo_insumo'),
        ),
    ]
